export const BASE_URL: string = 'https://norma.nomoreparties.space/api';
export const MODAL_ROOT_SELECTOR: string = '#modal';
export const ACCESS_COOKIE_EXPIRES: number = 20 * 60;
export const REFRESH_COOKIE_EXPIRES: number = 7 * 24 * 60 * 60;

export enum KEYBOARD_KEYS {
  ESCAPE = 'Escape',
}

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' =
  'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' =
  'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' =
  'GET_INGREDIENTS_FAILED';

export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT: 'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT';
export const MOVE_INGREDIENT: 'MOVE_INGREDIENT' = 'MOVE_INGREDIENT';
export const CLEAR_CONSTRUCTOR: 'CLEAR_CONSTRUCTOR' = 'CLEAR_CONSTRUCTOR';

export const CHECKOUT_REQUEST: 'CHECKOUT_REQUEST' = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS' = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILED: 'CHECKOUT_FAILED' = 'CHECKOUT_FAILED';

export const SET_CURRENT_TAB: 'SET_CURRENT_TAB' = 'SET_CURRENT_TAB';

export const GET_USER_REQUEST_FAILED: 'GET_USER_REQUEST_FAILED' =
  'GET_USER_REQUEST_FAILED';
export const GET_USER_REQUEST_SUCCESS: 'GET_USER_REQUEST_SUCCESS' =
  'GET_USER_REQUEST_SUCCESS';

export const USER_REQUEST: 'USER_REQUEST' = 'USER_REQUEST';
export const USER_REQUEST_FAILED: 'USER_REQUEST_FAILED' = 'USER_REQUEST_FAILED';
export const USER_REQUEST_SUCCESS: 'USER_REQUEST_SUCCESS' =
  'USER_REQUEST_SUCCESS';

export const USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS' = 'USER_LOGOUT_SUCCESS';

export const GET_RESET_CODE_SUCCESS: 'GET_RESET_CODE_SUCCESS' =
  'GET_RESET_CODE_SUCCESS';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' =
  'RESET_PASSWORD_SUCCESS';

// ws
export const WS_CONNECTION_START_ALL: 'WS_CONNECTION_START_ALL' = 'WS_CONNECTION_START_ALL';
export const WS_CONNECTION_START_PERSON: 'WS_CONNECTION_START_PERSON' = 'WS_CONNECTION_START_PERSON';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' =
  'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' =
  'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_CLOSE: 'WS_CLOSE' = 'WS_CLOSE';

export const WS_URL: string = 'wss://norma.nomoreparties.space/orders';
